spring:
  kafka:
    bootstrap-servers: localhost:9092
    
aws:
  region: us-east-1
  msk:
    cluster-arn: arn:aws:kafka:us-east-1:123456789012:cluster/test-cluster/12345678-1234-1234-1234-123456789012-1
    role-arn: arn:aws:iam::987654321098:role/MSKCrossAccountRole
    topic-name: connectivity-test
    
logging:
  level:
    root: INFO
    com.example.msk: DEBUG
    org.apache.kafka: DEBUG
    
server:
  port: 8080